language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
sudo: false

before_install:
  - cpanm -n Devel::Cover::Report::Coveralls
after_script:
  - cover -test -report coveralls